//action type

export const FLUSH_DATA = "FLUSH_DATA";
export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const LOGOUT = "LOGOUT";

// export const SUPPORT_CREATE="SUPPORT_CREATE";
export const RESETPASSWORD = "RESETPASSWORD";

//SERVER RESPONSE AGANIST CERTAIN ACTIVITY
export const SUPPORT_RESP = "SUPPORT_RESP";
export const REGISTER_RESP = "REGISTER_RESP";
export const LOGIN_RESP = "LOGIN_RESP";
export const RESETPASSWORD_RESP = "RESETPASSWORD_RESP";
export const VALIDATEOTP_RESP = "VALIDATEOTP_RESP";
export const RESENDOTP_RESP = "VALIDATEOTP_RESP";

export const EDIT_USERFIELD_MODE = "EDIT_USERFIELD_MODE";
export const USER_FIELDMODE_SAVE_RESP = "USER_FIELDMODE_SAVE_RESP";
export const USER_FIELDMODE_FETCH_RESP = "USER_FIELDMODE_FETCH_RESP";
export const USER_FIELDMODE_DELETE_RESP = "USER_FIELDMODE_DELETE_RESP";

export const PROJECT_TEMPLATE_RESP = "PROJECT_TEMPLATE_RESP";
export const SHOW_TEMPLATE_RESP = "SHOW_TEMPLATE_RESP";
export const TEMPLATE_PAGE_RESP = "TEMPLATE_PAGE_RESP";
export const EDIT_TEMPLATE_RESP = "EDIT_TEMPLATE_RESP";
export const EDIT_EXECUTE_RESP = "EDIT_EXECUTE_RESP";

export const PROJECT_DETAILS_RESP = "PROJECT_DETAILS_RESP";
export const PROJECT_DETAILS_FETCH_RESP = "PROJECT_DETAILS_FETCH_RESP";
export const PROJECT_DETAILS_POST_RESP = "PROJECT_DETAILS_POST_RESP";
export const PROJECT_DETAILS_DELETE_RESP = "PROJECT_DETAILS_DELETE_RESP";

export const GET_EXISTING_PROJECT_RESP = "GET_EXISTING_PROJECT_RESP";

export const PROJECT_BRIEF_FETCH_RESP = "PROJECT_BRIEF_FETCH_RESP";
export const PROJECT_BRIEF_POST_RESP = "PROJECT_BRIEF_POST_RESP";
export const PROJECT_BRIEF_DELETE_RESP = "PROJECT_BRIEF_DELETE_RESP";

export const USER_DESIGNATION_FETCH_RESP = "USER_DESIGNATION_RESP";
export const USER_DESIGNATION_RESP = "USER_DESIGNATION_RESP";
export const USER_DESIGNATION_CREATE_RESP = "USER_DESIGNATION_CREATE_RESP";
export const FETCH_PROJECT_DETAILS_RESP = "FETCH_PROJECT_DETAILS_RESP";

export const GET_PROJECT = "GET_PROJECT";
export const NEW_PROJECT = "NEW_PROJECT";

export const PROJECT_FLAG = "PROJECT_FLAG";

export const CLIENT_FETCH_RESP = "CLIENT_FETCH_RESP";

//LAYOUT AND UTILS
export const LOADING = "LOADING";
export const SERVER_ERROR = "SERVER_ERROR";
export const HIDE_ERROR_MODAL = "HIDE_ERROR_MODAL";
export const HIDE_SERVERSTATUS_MODAL = "HIDE_SERVERSTATUS_MODAL";
export const HIDE_PROJECT_SIDEBAR = "HIDE_PROJECT_SIDEBAR";
export const HIDE_RESOURCES_SIDEBAR = "HIDE_RESOURCES_SIDEBAR";
export const SHOW_PROJECT_SIDEBAR = "SHOW_PROJECT_SIDEBAR";
export const SHOW_RESOURCES_SIDEBAR = "SHOW_RESOURCES_SIDEBAR";
export const HIDE_LOADER = "HIDE_LOADER";
